model_parameters:
  training_range: 
    start_date: "2024-04-01"
    end_date: "2024-05-01"
  validation_range: 
    start_date: "2024-05-02"
    end_date: "2024-05-12"
  test_range: 
    start_date: "2024-05-13"
    end_date: "2024-05-20"
  interval: 
    type: "h2"
  sequence_len: 24
  num_values: 50
  threshold: 0.33
  crypto_coin: "dogecoin"