model_parameters:
  training_range: 
    start_date: "01/04/2024"
    end_date: "01/05/2024"
  validation_range: 
    start_date: "02/05/2024"
    end_date: "12/05/2024"
  test_range: 
    start_date: "13/05/2024"
    end_date: "20/05/2024"
  interval: 
    type: "h2"
  sequence_len: 24
  num_values: 50
  threshold: 0.33
  crypto_coin: "dogecoin"