services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-root}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
