version: '3'
services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-root}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data