version: '3.8'

services:
  python:
    build:
      context: /workspaces/project-RedPandaMC/.devcontainer
      dockerfile: Dockerfile
    command:
      - sleep
      - infinity
    container_name: dev_python
    depends_on:
      postgres:
        condition: service_started
    environment:
      CONDA_DEFAULT_ENV: mlops_project_env
    volumes:
      - type: bind
        source: /workspaces/project-RedPandaMC/.devcontainer
        target: /workspaces
        bind:
          propagation: shared
    networks:
      - mynetwork
    ports:
      - "4200:4200"
      - "5000:5000"
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: dev_postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge