version: '3.8'

services:
  python:
    build:
      context: /workspaces/project-RedPandaMC/.devcontainer
      dockerfile: Dockerfile
    command:
      - sleep
      - infinity
    container_name: dev_python
    depends_on:
      postgres:
        condition: service_started
    environment:
      CONDA_DEFAULT_ENV: mlops_project_env
    volumes:
      - type: bind
        source: /workspaces/project-RedPandaMC/.devcontainer
        target: /workspace
        bind:
          create_host_path: true

  postgres:
    image: postgres:latest
    container_name: dev_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
