name: mlops_project_env
channels:
  - defaults
dependencies:
  - python=3.11
  - black
  - ipykernel
  - jupyter
  - keras
  - matplotlib
  - mlflow
  - notebook
  - numpy
  - pandas
  - psycopg2
  - python-dotenv
  - requests
  - seaborn
  - sqlalchemy
  - tensorflow
  - pip
  - pip:
    - evidently
