name: mlops_project_env
channels:
  - defaults
dependencies:
  - python=3.11
  - psycopg2
  - numpy
  - pandas
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - seaborn
  - requests